spring:
  application:
    name: eureka-server
# logging:
#   level:
#     root: debug

---
spring:
  config:
    activate:
      on-profile: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server-peer1
  client:
    service-url:
      defaultZone: http://eureka-server-peer2:8762/eureka,http://eureka-server-peer3:8763/eureka

---
spring:
  config:
    activate:
      on-profile: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka-server-peer2
  client:
    service-url:
      defaultZone: http://eureka-server-peer1:8761/eureka,http://eureka-server-peer3:8763/eureka

---
spring:
  config:
    activate:
      on-profile: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: eureka-server-peer3
  client:
    service-url:
      defaultZone: http://eureka-server-peer1:8761/eureka,http://eureka-server-peer2:8762/eureka